complete -c shitfetch -s h -l help -d 'Show help'
complete -c shitfetch -s v -l version -d 'Show version'
complete -c shitfetch -s l -l logo -r -a 'auto none' -d 'Set logo'
complete -c shitfetch -s t -l template -r -a 'default mini' -d 'Set template'
complete -c shitfetch -l modules -r -a 'os kernel init uptime host shell wm dewm wm/de term terminal cpu gpu memory swap disk packages pkgs display locale lang local-ip local_ip ip' -d 'Set module order'
complete -c shitfetch -s c -l config -r -F -d 'Load config file'
complete -c shitfetch -l no-config -d 'Skip automatic config loading'
complete -c shitfetch -l spin -a 'x y xy' -d 'Animate the logo as spinning 2.5D relief'
complete -c shitfetch -l spin-speed -r -d 'Rotation radians per second (0.05-20)'
complete -c shitfetch -l spin-size -r -d 'Projection scale (0.5-5)'
complete -c shitfetch -l spin-depth -r -d 'Relief thickness (0.1-10, 0 = auto)'
complete -c shitfetch -l spin-height -r -d 'Relief rows (6-200, 0 = auto)'
complete -c shitfetch -l spin-frames -r -d 'Stop after N frames'
complete -c shitfetch -l spin-fps -r -d 'Target frame rate (1-120)'
complete -c shitfetch -l spin-light -r -a 'top-left top top-right left front right bottom-left bottom bottom-right' -d 'Light direction'
complete -c shitfetch -l spin-shade -r -a 'auto ascii braille blocks' -d 'Relief glyph alphabet'
complete -c shitfetch -l spin-chars -r -d 'Shading ramp, darkest first'
